# Generated by Django 2.2.9 on 2021-01-22 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20200722_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='projects.Project')),
            ],
        ),
    ]
