# Generated by Django 2.2.9 on 2021-01-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_projectlinks_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlinks',
            name='text',
            field=models.CharField(default='Link', max_length=100),
        ),
    ]
