# Generated by Django 2.2.9 on 2021-01-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20210122_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlinks',
            name='text',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
