# Generated by Django 3.0.8 on 2020-07-19 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200719_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectDescription',
        ),
    ]
