# Generated by Django 3.0.8 on 2020-07-20 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
