# Generated by Django 3.0.8 on 2020-07-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0003_education_educationcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='educationCategory',
            new_name='categoryId',
        ),
    ]
