# Generated by Django 3.0.8 on 2020-07-22 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sssiteimages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteImage',
            new_name='SSSiteImage',
        ),
    ]
