# Generated by Django 3.0.8 on 2020-07-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200708_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='descrition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
