# Generated by Django 3.0.8 on 2020-07-22 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EducationDocumentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentImage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('document', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='educations.EducationDocument')),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/education'),
        ),
        migrations.DeleteModel(
            name='EducationImage',
        ),
        migrations.AddField(
            model_name='educationdocument',
            name='education',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='educations.Education'),
        ),
    ]
