# Generated by Django 3.0.8 on 2020-07-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0002_auto_20200722_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdocument',
            name='documentImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='EducationDocumentImage',
        ),
    ]
