# Generated by Django 3.0.8 on 2020-07-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0003_auto_20200722_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationdocument',
            name='documentImage',
        ),
        migrations.AddField(
            model_name='educationdocument',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
